{
 "title": "My Demo RED2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(http_requests_total[1m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(http_requests_error_total[1m])) / sum(rate(http_requests_total[1m])))",
     "legendFormat": "Error %"
    }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_ms_bucket[5m]))",
     "legendFormat": "p95 Latency"
    }
   ]
  },
  {
   "title": "Logs Table ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"demo-app\"}"
    }
   ]
  }
 ]
}